
title: Animales más mortíferos
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
search_enabled: false
color_scheme: dark

# Aux links for the upper right navigation
aux_links:
  "Alianza Global para el Control de la Rabia":
    - "https://rabiesalliance.org/"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false
