
title: Animales más mortíferos
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
search_enabled: false
color_scheme: dark


logo: "https://www.google.com/imgres?q=animales%20mortiferos&imgurl=https%3A%2F%2Ft1.ea.ltmcdn.com%2Fes%2Fposts%2F1%2F0%2F7%2Flos_animales_mas_peligrosos_del_mundo_22701_orig.jpg&imgrefurl=https%3A%2F%2Fwww.expertoanimal.com%2Flos-animales-mas-peligrosos-del-mundo-22701.html&docid=N_Ul42bALkFblM&tbnid=OrT_PY0qqiPjgM&vet=12ahUKEwirwuvskpWJAxUpR_EDHXOHHqAQM3oECGoQAA..i&w=1200&h=800&hcb=2&ved=2ahUKEwirwuvskpWJAxUpR_EDHXOHHqAQM3oECGoQAA"


